# -*- coding:utf-8 -*-
{
    'name': 'BSD Quản lý dịch vụ cư dân',
    'version': '0.1',
    'category': 'App',
    'author': 'Thịnh Lưu',
    'depends': [
                'base',
                'bsd_residential',
                'product',
                'sale_management',
                'portal'
    ],
    'data': [
        'security/user_groups.xml',
        'security/bsd_security.xml',
        'security/ir.model.access.csv',
        'data/bsd_service_request_data.xml',
        'views/account_move_views.xml',
        'views/bsd_residential_vehicle_views.xml',
        'views/bsd_residential_electric_views.xml',
        'views/bsd_residential_water_views.xml',
        'views/bsd_residential_gym_views.xml',
        'views/bsd_residential_tennis_views.xml',
        'views/bsd_residential_bbq_views.xml',
        'views/bsd_residential_transfer_views.xml',
        'views/bsd_residential_swim_views.xml',
        'wizards/bsd_unit_create_invoice_views.xml',
        'wizards/bsd_block_create_invoice_views.xml',
        'wizards/bsd_wizard_create_gym_views.xml',
        'wizards/bsd_wizard_gym_pause_views.xml',
        'wizards/bsd_wizard_gym_run_views.xml',
        'wizards/bsd_wizard_create_swim_views.xml',
        'wizards/bsd_wizard_swim_pause_views.xml',
        'wizards/bsd_wizard_swim_run_views.xml',
        'views/menu_item_views.xml',
        'views/product_pricelist_views.xml',
        'views/bsd_unit_views.xml',
        'reports/report_gia_bao_phi_views.xml',
        'views/bsd_residential_check_service_gym_template.xml',
    ],
    'application': True,
}