# -*- coding:utf-8 -*-
{
    'name': 'BSD Quản lý cư dân',
    'version': '0.1',
    'category': 'App',
    'author': 'Thịnh Lưu',
    'depends': [
                'base',
                'bsd_block',
                'contacts',
                'sale',
    ],
    'data': [
        'security/user_groups.xml',
        'security/bsd_security.xml',
        'security/ir.model.access.csv',
        'data/bsd_registry_request_data.xml',
        'wizards/bsd_residential_wizard_views.xml',
        'wizards/bsd_wizard_create_card_views.xml',
        'wizards/bsd_wizard_request_refuse_views.xml',
        'views/bsd_unit_views.xml',
        'views/bsd_residential_views.xml',
        'views/res_partner_views.xml',
        'views/bsd_registry_request_views.xml',
        'views/bsd_registry_card_views.xml',
        'views/menu_item_views.xml',
        'views/bsd_contact_views.xml',
        'views/sale_order_views.xml',
    ],
    'application': True,
    'auto_install': True,
}